!COMCON-Physics and machine constants (mks)
!  clight-speed of light in vacuum (m/s)
!  coulom-elementary charge (coulomb)
!  elemas-electron mass (kg)
!  epsilo-permittivity of free space (farad/m)
!  pi-pi
!  promas-proton mass (kg)
!  xj7kv-unit conversion constant (joules/keV)
!  xmachp-computed machine precision
!  xmuo-permeability of free space (henry/m)
      REAL           clight,                  coulom,          
     #               elemas,                  epsilo,
     #               pi,                      promas,
     #               xj7kv,                   xmachp,
     #               xmuo
      COMMON/COMCON/ clight,                  coulom,          
     #               elemas,                  epsilo,          
     #               pi,                      promas,
     #               xj7kv,                   xmachp,
     #               xmuo     
